# Generated by Django 2.0.2 on 2018-04-12 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180412_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='achieved_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
